### ISSUE TITLE
Wrong package name in readme file

### ISSUE THREAD

**Issue by elboletaire** [eclyptox/SyliusRedsysPlugin#2]
The readme file says to install `eclyptox/redsys-plugin`, but the real name is `eclyptox/sylius-redsys-plugin`.

**Comment by eclyptox** [comment]
Thank you very much @elboletaire

**Comment by elboletaire** [comment]
I still haven't been able to properly try it with redsys api (it will take me some time, since their sandbox mode stinks, and I'll end up trying it on a production environment directly), but it really looks promising, and your plugin saved me a lot of time, so **thank you** 😃
